// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdeIwZ6jEJpTstTAlIV0YLdA5_jAm8OKo',
    appId: '1:667343975387:web:7f74bbf8c16fdab788edfe',
    messagingSenderId: '667343975387',
    projectId: 'simulador-unifique',
    authDomain: 'simulador-unifique.firebaseapp.com',
    storageBucket: 'simulador-unifique.appspot.com',
    measurementId: 'G-KJVX4YNTSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQPHFCij4cVfox6TT29_Z_6H5Z-Hfq2ZQ',
    appId: '1:667343975387:android:7ba90077b0eb1ba788edfe',
    messagingSenderId: '667343975387',
    projectId: 'simulador-unifique',
    storageBucket: 'simulador-unifique.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDt0jMV6GhPMzooElLZ6rUyZpSd5xANmg',
    appId: '1:667343975387:ios:c40151973bda3ed688edfe',
    messagingSenderId: '667343975387',
    projectId: 'simulador-unifique',
    storageBucket: 'simulador-unifique.appspot.com',
    iosClientId: '667343975387-3oo4qfl1q630cvuvkeisp6pmsa2m9rbn.apps.googleusercontent.com',
    iosBundleId: 'com.ssoft.simuladorUnifique',
  );
}
